export const iconAssets = {
  account: new URL('./Account.svg', import.meta.url).href,
  arrowDown: new URL('./ArrowDown.svg', import.meta.url).href,
  arrowLeft: new URL('./ArrowLeft.svg', import.meta.url).href,
  arrowRight: new URL('./ArrowRight.svg', import.meta.url).href,
  arrowRightNarrow: new URL('./ArrowRightNarrow.svg', import.meta.url).href,
  arrowUp: new URL('./ArrowUp.svg', import.meta.url).href,
  circleError: new URL('./CircleError.svg', import.meta.url).href,
  cross: new URL('./Cross.svg', import.meta.url).href,
  facebook: new URL('./Facebook.svg', import.meta.url).href,
  flag: new URL('./Flag.svg', import.meta.url).href,
  info: new URL('./Info.svg', import.meta.url).href,
  instagram: new URL('./Instagram.svg', import.meta.url).href,
  notification: new URL('./Notification.svg', import.meta.url).href,
  pensil: new URL('./Pensil.svg', import.meta.url).href,
  person: new URL('./Person.svg', import.meta.url).href,
  play: new URL('./Play.svg', import.meta.url).href,
  plusThin: new URL('./PlusThin.svg', import.meta.url).href,
  plusWide: new URL('./PlusWide.svg', import.meta.url).href,
  presetLeavingSoon: new URL('./presets-labels/LeavingSoon.svg', import.meta.url).href,
  presetNewSeason: new URL('./presets-labels/NewSeason.svg', import.meta.url).href,
  presetRecentlyAdded: new URL('./presets-labels/RecentlyAdded.svg', import.meta.url).href,
  presetTop10: new URL('./presets-labels/Top10.svg', import.meta.url).href,
  presetTop10Number: new URL('./presets-labels/Top10+#.svg', import.meta.url).href,
  question: new URL('./Question.svg', import.meta.url).href,
  ratingG: new URL('./maturity-ratings/G.svg', import.meta.url).href,
  ratingNc17: new URL('./maturity-ratings/NC-17.svg', import.meta.url).href,
  ratingPg: new URL('./maturity-ratings/PG.svg', import.meta.url).href,
  ratingPg13: new URL('./maturity-ratings/PG-13.svg', import.meta.url).href,
  ratingR: new URL('./maturity-ratings/R.svg', import.meta.url).href,
  ratingTv14: new URL('./maturity-ratings/TV-14.svg', import.meta.url).href,
  ratingTvG: new URL('./maturity-ratings/TV-G.svg', import.meta.url).href,
  ratingTvMa: new URL('./maturity-ratings/TV-MA.svg', import.meta.url).href,
  ratingTvPg: new URL('./maturity-ratings/TV-PG.svg', import.meta.url).href,
  ratingTvY: new URL('./maturity-ratings/TV-Y.svg', import.meta.url).href,
  ratingTvY7: new URL('./maturity-ratings/TV-Y7.svg', import.meta.url).href,
  search: new URL('./Search.svg', import.meta.url).href,
  videoQuality4k: new URL('./video-quality/4K.svg', import.meta.url).href,
  videoQualityDolbyVision: new URL('./video-quality/DolbyVision.svg', import.meta.url).href,
  videoQualityHd: new URL('./video-quality/HD.svg', import.meta.url).href,
  videoQualityHdr: new URL('./video-quality/HDR.svg', import.meta.url).href,
  videoQualityUltraHd4k: new URL('./video-quality/UltraHD4K.svg', import.meta.url).href,
  thumbDown: new URL('./ThumbDown.svg', import.meta.url).href,
  thumbUp: new URL('./ThumbUp.svg', import.meta.url).href,
  twitter: new URL('./Twitter.svg', import.meta.url).href,
  youTube: new URL('./YouTube.svg', import.meta.url).href,
} as const;

export type IconName = keyof typeof iconAssets;

export const getIconAsset = (name: IconName): string => iconAssets[name];
