import { runSeedWithData } from './seed.js';

const mockSeedData = {
  admins: [
    {
      id: 'admin-1',
      username: 'admin',
      password: 'admin123',
    },
  ],
  events: [
    {
      id: 'event-public-1',
      title: 'Flix MVP Launch Event',
      slug: 'flix-mvp-launch-event',
      description: 'Public event used as baseline for learner catalog/playback flow.',
      shortDescription: 'Aprenda em trilhas curtas com checkpoints práticos.',
      longDescription:
        'Evento público base para o fluxo de catálogo e playback. Trilha prática para validação, analytics e oferta com foco em execução.',
      isActive: 1,
      visibility: 'public',
      accessKey: null,
      heroTitle: 'Bem-vindo ao Flix',
      heroSubtitle: 'Aprenda em trilhas curtas com checkpoints praticos.',
      heroCtaText: 'Comecar',
      highlightVideoUrl: 'https://www.youtube.com/watch?v=BKZ_Bkl324Y&t=25s',
      backgroundColor: '#0f172a',
      textColor: '#f8fafc',
      accentColor: '#22d3ee',
    },
    {
      id: 'event-private-1',
      title: 'Flix Growth Intensive',
      slug: 'flix-growth-intensive',
      description: 'Private event baseline with access key protected lessons.',
      shortDescription: 'Conteúdo privado para alunos convidados.',
      longDescription:
        'Evento privado com acesso por chave. Conteúdo avançado para crescimento, aquisição e escala em campanhas e produto.',
      isActive: 1,
      visibility: 'private',
      accessKey: 'growth2026',
      heroTitle: 'Acesso exclusivo',
      heroSubtitle: 'Conteudo privado para alunos convidados.',
      heroCtaText: 'Entrar com chave',
      highlightVideoUrl: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
      backgroundColor: '#111111',
      textColor: '#f5f5f5',
      accentColor: '#e50914',
    },
    {
      id: 'event-public-2',
      title: 'Flix Creator Community Week',
      slug: 'flix-creator-community-week',
      description: 'Open event for community engagement and public previews.',
      shortDescription: 'Conteúdos abertos para aquecer a comunidade.',
      longDescription:
        'Evento aberto para engajamento da comunidade com aulas e materiais de aquecimento, preparando para trilhas e ofertas futuras.',
      isActive: 1,
      visibility: 'public',
      accessKey: null,
      heroTitle: 'Comunidade Flix',
      heroSubtitle: 'Conteudos abertos para aquecer o funil.',
      heroCtaText: 'Explorar trilha',
      highlightVideoUrl: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
      backgroundColor: '#172554',
      textColor: '#eff6ff',
      accentColor: '#38bdf8',
    },
  ],
  lessons: [
    {
      id: 'lesson-public-1',
      eventId: 'event-public-1',
      title: 'Kickoff do MVP',
      description: 'Abertura da trilha com visão do MVP, metas e próximos passos.',
      slug: 'kickoff-do-mvp',
      videoProvider: 'youtube',
      videoId: 'dQw4w9WgXcQ',
      releaseAt: '2025-01-01T10:00:00.000Z',
      expiresAt: null,
    },
    {
      id: 'lesson-public-2',
      eventId: 'event-public-1',
      title: 'Analytics na pratica',
      description: 'Configuração de métricas essenciais e leitura de indicadores.',
      slug: 'analytics-na-pratica',
      videoProvider: 'vimeo',
      videoId: '148751763',
      releaseAt: '2025-01-03T10:00:00.000Z',
      expiresAt: null,
    },
    {
      id: 'lesson-public-3',
      eventId: 'event-public-1',
      title: 'Oferta irresistivel',
      description: 'Construção da oferta com proposta de valor clara e objetiva.',
      slug: 'oferta-irresistivel',
      videoProvider: 'youtube',
      videoId: 'M7lc1UVf-VE',
      releaseAt: '2099-01-10T10:00:00.000Z',
      expiresAt: null,
    },
    {
      id: 'lesson-public-4',
      eventId: 'event-public-1',
      title: 'Replay da live',
      description: 'Resumo da live com decisões e ajustes aplicados no projeto.',
      slug: 'replay-da-live',
      videoProvider: 'gemini_stream',
      videoId: 'gemini-replay-001',
      releaseAt: '2025-01-04T10:00:00.000Z',
      expiresAt: '2025-01-06T10:00:00.000Z',
    },
    {
      id: 'lesson-private-1',
      eventId: 'event-private-1',
      title: 'Growth Playbook',
      description: 'Playbook de crescimento com testes de aquisição e retenção.',
      slug: 'growth-playbook',
      videoProvider: 'youtube',
      videoId: 'aqz-KE-bpKQ',
      releaseAt: '2025-01-10T10:00:00.000Z',
      expiresAt: null,
    },
    {
      id: 'lesson-private-2',
      eventId: 'event-private-1',
      title: 'Escala de anuncios',
      description: 'Estratégias para escalar campanhas mantendo eficiência de CAC.',
      slug: 'escala-de-anuncios',
      videoProvider: 'youtube',
      videoId: 'ysz5S6PUM-U',
      releaseAt: '2099-02-01T10:00:00.000Z',
      expiresAt: null,
    },
    {
      id: 'lesson-community-1',
      eventId: 'event-public-2',
      title: 'Aula aberta de aquecimento',
      description: 'Aquecimento da comunidade com contexto e plano da semana.',
      slug: 'aula-aberta-aquecimento',
      videoProvider: 'youtube',
      videoId: 'iik25wqIuFo',
      releaseAt: '2025-02-01T10:00:00.000Z',
      expiresAt: null,
    },
  ],
  materials: [
    {
      id: 'material-public-1',
      eventId: 'event-public-1',
      lessonId: 'lesson-public-1',
      fileName: 'mvp-kickoff-slides.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 420000,
      downloadUrl: 'https://cdn.flix.local/materials/mvp-kickoff-slides.pdf',
    },
    {
      id: 'material-public-2',
      eventId: 'event-public-1',
      lessonId: 'lesson-public-2',
      fileName: 'analytics-dashboard-checklist.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 368000,
      downloadUrl: 'https://cdn.flix.local/materials/analytics-dashboard-checklist.pdf',
    },
    {
      id: 'material-private-1',
      eventId: 'event-private-1',
      lessonId: 'lesson-private-1',
      fileName: 'growth-playbook-notes.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 512000,
      downloadUrl: 'https://cdn.flix.local/materials/growth-playbook-notes.pdf',
    },
    {
      id: 'material-community-1',
      eventId: 'event-public-2',
      lessonId: 'lesson-community-1',
      fileName: 'community-week-roadmap.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 289000,
      downloadUrl: 'https://cdn.flix.local/materials/community-week-roadmap.pdf',
    },
  ],
  quizzes: [
    {
      id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7001',
      eventId: 'event-public-1',
      lessonId: 'lesson-public-1',
      title: 'Quiz de Validacao do MVP',
      passPercentage: 70,
      questions: [
        {
          id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7101',
          prompt: 'Qual objetivo principal do MVP?',
          order: 1,
          options: [
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7201',
              text: 'Validar usabilidade e valor rapido',
              isCorrect: 1,
            },
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7202',
              text: 'Cobrir todos os recursos finais',
              isCorrect: 0,
            },
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7203',
              text: 'Focar apenas em identidade visual',
              isCorrect: 0,
            },
          ],
        },
        {
          id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7102',
          prompt: 'Qual fluxo deve estar completo no MVP?',
          order: 2,
          options: [
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7211',
              text: 'Apenas cadastro',
              isCorrect: 0,
            },
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7212',
              text: 'Admin e learner ponta a ponta',
              isCorrect: 1,
            },
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7213',
              text: 'Apenas dashboard administrativo',
              isCorrect: 0,
            },
          ],
        },
      ],
    },
    {
      id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7002',
      eventId: 'event-private-1',
      lessonId: 'lesson-private-1',
      title: 'Quiz de Growth',
      passPercentage: 60,
      questions: [
        {
          id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7301',
          prompt: 'Qual metrica mede custo de aquisicao por cliente?',
          order: 1,
          options: [
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7311',
              text: 'CAC',
              isCorrect: 1,
            },
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7312',
              text: 'NPS',
              isCorrect: 0,
            },
            {
              id: '8e7f4c4d-8e8f-4f38-8b8e-6a8f3c9a7313',
              text: 'Churn',
              isCorrect: 0,
            },
          ],
        },
      ],
    },
  ],
};

export const runMockSeed = async ({ databaseUrl = process.env.DATABASE_URL } = {}) =>
  runSeedWithData({ databaseUrl, seedData: mockSeedData });
